#!/bin/bash

b=`cat /tmp/value.txt`
[[ $b == "1.0" ]] && b="100"

b=$((b $1))

[[ $b -lt 10 ]] && b=10
[[ $b -gt 100 ]] && b=100

if [[ $b -eq 100 ]]; then
	b=1.0
else
	b=0.$b
fi


outputs=( "HDMI-1" "HDMI-3" "HDMI-2" )
for i in "${outputs[@]}"; do
    gnome-randr adjust $i --brightness $b
done

echo $b | sed 's/0.//' > /tmp/value.txt

